const list = {
  BOUGHT: 1,
  SHOW: 0.7,
  CATEGORY_SHOW: 0.25,
  GENDER_COMP: 1.2,
  GENGER_NOT_COMP: 0.15,
  IDENTICAL_CATEGORY: 1.5,
  CATEGORIES_SIMILARITY: 0.3,
  USER_SIMILARITY: 2,
  ACTION: 0.1,
  TOP_PRODUCTS_COUNT: 10,
  USER_PRODUCTS_COUNT: 20,
};

module.exports = list;
