const ProductActionTypes = {
  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
  FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_FAILURE: "FETCH_PRODUCTS_FAILURE",
  FETCH_ONE_PRODUCT_START: "FETCH_ONE_PRODUCT_START",
  FETCH_ONE_PRODUCT_SUCCESS: "FETCH_ONE_PRODUCT_SUCCESS",
  FETCH_ONE_PRODUCT_FAILURE: "FETCH_ONE_PRODUCT_FAILURE",
  CREATE_PRODUCT_START: "CREATE_PRODUCT_START",
  CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
  CREATE_PRODUCT_FAILURE: "CREATE_PRODUCT_FAILURE",
  UPDATE_PRODUCT_START: "UPDATE_PRODUCT_START",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_FAILURE: "UPDATE_PRODUCT_FAILURE",
};

export default ProductActionTypes;
