const ProductActionTypes = {
  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
  FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_FAILURE: "FETCH_PRODUCTS_FAILURE",
  FETCH_ONE_PRODUCT_START: "FETCH_ONE_PRODUCT_START",
  FETCH_ONE_PRODUCT_SUCCESS: "FETCH_ONE_PRODUCT_SUCCESS",
  FETCH_ONE_PRODUCT_FAILURE: "FETCH_ONE_PRODUCT_FAILURE",
  FETCH_TOP_PRODUCTS_START: "FETCH_TOP_PRODUCTS_START",
  FETCH_TOP_PRODUCTS_SUCCESS: "FETCH_TOP_PRODUCTS_SUCCESS",
  FETCH_TOP_PRODUCTS_FAILURE: "FETCH_TOP_PRODUCTS_FAILURE",
  SEND_REVIEW_START: "SEND_REVIEW_START",
  SEND_REVIEW_SUCCESS: "SEND_REVIEW_SUCCESS",
  SEND_REVIEW_FAILURE: "SEND_REVIEW_FAILURE",
};

export default ProductActionTypes;
