const addressTypes = {
  FETCH_ADDRESS_START: "FETCH_ADDRESS_START",
  FETCH_ADDRESS_SUCCESS: "FETCH_ADDRESS_SUCCESS",
  FETCH_ADDRESS_FAILURE: "FETCH_ADDRESS_FAILURE",
  CREATE_ADDRESS: "CREATE_ADDRESS",
  CREATE_ADDRESS_FAILURE: "CREATE_ADDRESS_FAILURE",
  CREATE_INVOICE: "CREATE_INVOICE",
  SELECT_ADDRESS: "SELECT_ADDRESS",
  SELECT_INVOICE: "SELECT_INVOICE",
  SELECT_INVOICE_ADDRESS: "SELECT_INVOICE_ADDRESS",
  ACTIVATE_INVOICE: "ACTIVATE_INVOICE",
  DELETE_ADDRESS_START: "DELETE_ADDRESS_START",
  DELETE_ADDRESS_SUCCESS: "DELETE_ADDRESS_SUCCESS",
  DELETE_ADDRESS_FAILURE: "DELETE_ADDRESS_FAILURE",
};

export default addressTypes;
