const addressTypes = {
  FETCH_ADDRESS_START: "FETCH_ADDRESS_START",
  FETCH_ADDRESS_SUCCESS: "FETCH_ADDRESS_SUCCESS",
  FETCH_ADDRESS_FAILURE: "FETCH_ADDRESS_FAILURE",
  CREATE_ADDRESS: "CREATE_ADDRESS",
  CREATE_INVOICE: "CREATE_INVOICE",
  SEELCT_ADDRESS: "SEELCT_ADDRESS",
  SELECT_INVOICE: "SELECT_INVOICE",
};

export default addressTypes;
