const RecommendationsActionTypes = {
  FETCH_RECOMMENDATIONS_START: "FETCH_RECOMMENDATIONS_START",
  FETCH_RECOMMENDATIONS_SUCCESS: "FETCH_RECOMMENDATIONS_SUCCESS",
  FETCH_RECOMMENDATIONS_FAILURE: "FETCH_RECOMMENDATIONS_FAILURE",
  FETCH_SIMILAR_PRODUCTS_START: "FETCH_SIMILAR_PRODUCTS_START",
  FETCH_SIMILAR_PRODUCTS_SUCCESS: "FETCH_SIMILAR_PRODUCTS_SUCCESS",
  FETCH_SIMILAR_PRODUCTS_FAILURE: "FETCH_SIMILAR_PRODUCTS_FAILURE",
  FETCH_GENDER_BASED_RECOMMENDATIONS_START:
    "FETCH_GENDER_BASED_RECOMMENDATIONS_START",
  FETCH_GENDER_BASED_RECOMMENDATIONS_SUCCESS:
    "FETCH_GENDER_BASED_RECOMMENDATIONS_SUCCESS",
  FETCH_GENDER_BASED_RECOMMENDATIONS_ERROR:
    "FETCH_GENDER_BASED_RECOMMENDATIONS_ERROR",
};

export default RecommendationsActionTypes;
