const CartTypes = {
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
  SELECT_DELIVERY_TYPE: "SELECT_DELIVERY_TYPE",
  SELECT_PAYMENT_METHOD: "SELECT_PAYMENT_METHOD", 
};

export default CartTypes;
