const bookingTypes = {
  CREATE_BOOKING_START: "CREATE_BOOKING_START",
  CREATE_BOOKING_SUCCESS: "CREATE_BOOKING_SUCCESS",
  CREATE_BOOKING_FAILURE: "CREATE_BOOKING_FAILURE",
  FETCH_BOOKING_START: "FETCH_BOOKING_START",
  FETCH_BOOKING_SUCCESS: "FETCH_BOOKING_SUCCESS",
  FETCH_BOOKING_FAILURE: "FETCH_BOOKING_FAILURE",
  PAY_FOR_BOOKING_START: "PAY_FOR_BOOKING_START",
  PAY_FOR_BOOKING_SUCCESS: "PAY_FOR_BOOKING_SUCCESS",
  PAY_FOR_BOOKING_FAILURE: "PAY_FOR_BOOKING_FAILURE",
  FETCH_BOOKING_LIST_START: "FETCH_BOOKING_LIST_START",
  FETCH_BOOKING_LIST_SUCCESS: "FETCH_BOOKING_LIST_SUCCESS",
  FETCH_BOOKING_LIST_FAILURE: "FETCH_BOOKING_LIST_FAILURE",
};

export default bookingTypes;
