const bookingTypes = {
  CREATE_BOOKING_START: "CREATE_BOOKING_START",
  CREATE_BOOKING_SUCCESS: "CREATE_BOOKING_SUCCESS",
  CREATE_BOOKING_FAILURE: "CREATE_BOOKING_FAILURE",
  FETCH_BOOKING_START: "FETCH_BOOKING_START",
  FETCH_BOOKING_SUCCESS: "FETCH_BOOKING_SUCCESS",
  FETCH_BOOKING_FAILURE: "FETCH_BOOKING_FAILURE",
};

export default bookingTypes;
