const NewsletterTypes = {
  SUBSCRIBE_START: "SUBSCRIBE_START",
  SUBSCRIBE_SUCCESS: "SUBSCRIBE_SUCCESS",
  SUBSCRIBE_FAILURE: "SUBSCRIBE_FAILURE",
  UNSUBSCRIBE_START: "UNSUBSCRIBE_START",
  UNSUBSCRIBE_SUCCESS: "UNSUBSCRIBE_SUCCESS",
  UNSUBSCRIBE_FAILURE: "UNSUBSCRIBE_FAILURE",
  CLEAR_SUBSCRIPTION_STATUS: "CLEAR_SUBSCRIPTION_STATUS",
};

export default NewsletterTypes;
